Repository googleapis/cloud-debug-nodejs, pull requests merged in 2019-06, with the labels that each got.

#713 feat: support apiEndpoint override
  package.json
  src/agent/controller.ts
  src/client/stackdriver/debug.ts
  test/test-controller.ts
Labels: cla: yes

#718 chore: merge `options.debug` and `options`
  src/index.ts
Labels: cla: yes

#709 feat: add `get()` function
  src/index.ts
  test/test-module.ts
Labels: cla: yes, status: blocked

#704 chore: release 4.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, status: blocked, type: process

#720 refactor: run the formatter
  src/agent/config.ts
Labels: cla: yes

#721 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#722 fix(docs): add repo-metadata file
  .gitignore
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  synth.metadata
  synth.py
Labels: cla: yes

#723 chore: release 4.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#724 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes
