Repository googleapis/cloud-debug-nodejs, pull requests merged in 2019-03, with the labels that each got.

#644 Delete unused region tags
  samples/app.js
Labels: cla: yes

#645 chore: remove p-limit types
  package.json
  src/agent/io/sourcemapper.ts
Labels: cla: yes

#646 build: add configs to import keys for builds
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#647 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#648 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#651 Release @google-cloud/debug-agent v3.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#524 fix: use stableObjectId field for object equality in Node 10+
  src/agent/debuglet.ts
  src/agent/state/inspector-state.ts
  test/test-circular-code.js
  test/test-circular.ts
  test/test-debuglet.ts
Labels: :rotating_light:, cla: yes

#654 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#655 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes
