Repository googleapis/cloud-debug-nodejs, pull requests merged in 2019-05, with the labels that each got.

#676 Release @google-cloud/debug-agent v3.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#679 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#680 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#681 chore(deps): upgrade to gts 1.0.0
  package.json
  src/agent/config.ts
  src/agent/controller.ts
  src/agent/debuglet.ts
  src/agent/io/scanner.ts
  src/agent/io/sourcemapper.ts
  src/agent/state/inspector-state.ts
  src/agent/state/legacy-state.ts
  src/agent/util/debug-assert.ts
  src/agent/util/utils.ts
  src/agent/util/validator.ts
  src/agent/v8/debugapi.ts
  src/agent/v8/inspector-debugapi.ts
  src/agent/v8/legacy-debugapi.ts
  src/agent/v8/v8inspector.ts
  src/client/stackdriver/debug.ts
  src/client/stackdriver/status-message.ts
  src/debuggee.ts
  src/index.ts
  system-test/test-controller.ts
  system-test/test-e2e.ts
  system-test/test-install.ts
  test/auth-request.ts
  test/debugger.ts
  test/misc/bench.ts
  test/mock-logger.ts
  test/nocks.ts
  test/test-circular.ts
  test/test-controller.ts
  test/test-debug-assert.ts
  test/test-debuggee.ts
  test/test-debuglet.ts
  test/test-duplicate-expressions.ts
  test/test-duplicate-nested-expressions.ts
  test/test-evaluated-expressions.ts
  test/test-expression-side-effect.ts
  test/test-fat-arrow.ts
  test/test-max-data-size.ts
  test/test-module.ts
  test/test-options-credentials.ts
  test/test-scanner.ts
  test/test-sourcemapper.ts
  test/test-state.ts
  test/test-this-context.ts
  test/test-try-catch.ts
  test/test-v8debugapi-ts-code.ts
  test/test-v8debugapi.ts
Labels: cla: yes

#682 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#685 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  synth.py
Labels: cla: yes

#689 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#684 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#690 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#696 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#698 refactor: drop dependency on pify
  package.json
  scripts/setup-build-dir.ts
  src/agent/debuglet.ts
  src/agent/io/sourcemapper.ts
Labels: cla: yes

#699 chore: remove changelog maker
  bin/run-changelog.sh
  package.json
Labels: cla: yes

#700 refactor: attempt to remove request
  package.json
  src/client/stackdriver/debug.ts
  test/auth-request.ts
  test/test-controller.ts
Labels: cla: yes

#706 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#693 chore(deps): update @sindresorhus/is to ^0.17.0
  package.json
Labels: cla: yes

#710 chore: update @sindresorhus/is to 0.17.1
  package.json
Labels: cla: yes

#711 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#714 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#716 chore: cleanup unused files & `npm audit fix`
  .clang-format
  .npmignore
  AUTHORS
  appveyor.yml
  package.json
  repo-debug.log
  scripts-tsconfig.json
Labels: cla: yes
