Repository googleapis/cloud-debug-nodejs, pull requests merged in 2019-04, with the labels that each got.

#664 chore(deps): drop unused dependency on broken-link-checker-local
  package.json
Labels: automerge, cla: yes

#665 chore: drop duplicate nyc config
  package.json
Labels: automerge, cla: yes

#663 test: add smoke test for app sample
  samples/app.js
  samples/package.json
  samples/test/test.js
Labels: cla: yes

#675 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes

#671 Add debugger support for Cloud Run. See b/112087600 for context
  src/agent/debuglet.ts
  test/test-debuglet.ts
Labels: cla: yes, status: blocked
