Repository googleapis/cloud-debug-nodejs, pull requests merged in 2020-07, with the labels that each got.

#900 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#902 fix(deps): update dependency p-limit to v3
  package.json
  src/agent/io/sourcemapper.ts
Labels: cla: yes

#904 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#908 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#907 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#914 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#911 build: update protos
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none
