Repository googleapis/cloud-debug-nodejs, pull requests merged in 2020-12, with the labels that each got.

#935 build: use a consistent config
  .eslintignore
  .github/workflows/ci.yaml
  .mocharc.js
  package.json
  system-test/.eslintrc
  test/.eslintrc
  test/test-evaluated-expressions.ts
Labels: api: clouddebugger, cla: yes

#936 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: clouddebugger, cla: yes, context: full

#938 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: clouddebugger, automerge, cla: yes, context: full
