Repository googleapis/cloud-debug-nodejs, pull requests merged in 2020-05, with the labels that each got.

#876 fix: reduce set of dependencies
  package.json
  src/agent/io/scanner.ts
Labels: cla: yes

#875 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#877 chore: remove dependency on require-inject
  package.json
  test/test-state.ts
Labels: automerge, cla: yes
