Repository googleapis/cloud-debug-nodejs, pull requests merged in 2020-10, with the labels that each got.

#928 fix: add required parameter to fix build breakage.
  src/agent/state/legacy-state.ts
Labels: cla: yes

#929 build: update to latest build files
  .github/workflows/ci.yaml
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
  synth.py
  test/test-debug-assert.ts
Labels: api: clouddebugger, cla: yes

#930 docs: updated code of conduct (includes update to devsite generation)
  .kokoro/release/docs-devsite.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: clouddebugger, cla: yes, context: none
