Repository googleapis/cloud-debug-nodejs, pull requests merged in 2022-05, with the labels that each got.

#1067 feat: Add ability to store breakpoint data in firebase realtime database
  package.json
  src/agent/config.ts
  src/agent/controller.ts
  src/agent/debuglet.ts
  src/agent/firebase-controller.ts
  src/agent/oneplatform-controller.ts
  src/index.ts
  system-test/test-controller.ts
  test/test-controller.ts
  test/test-debuglet.ts
Labels: api: clouddebugger, size: xl

#1075 fix: Fix and re-enable previously broken tests
  src/agent/debuglet.ts
  test/test-debuglet.ts
  test/test-firebase-controller.ts
Labels: api: clouddebugger, size: s

#1077 fix: use debuglet's logger in the controller.
  src/agent/debuglet.ts
  src/agent/oneplatform-controller.ts
  system-test/test-controller.ts
  test/test-controller.ts
Labels: api: clouddebugger, size: m

#1076 feat!: Add ability to store breakpoint data in firebase realtime database
  package.json
  src/agent/config.ts
  src/agent/controller.ts
  src/agent/debuglet.ts
  src/agent/firebase-controller.ts
  src/agent/oneplatform-controller.ts
  src/index.ts
  system-test/test-controller.ts
  test/test-controller.ts
  test/test-debuglet.ts
  test/test-firebase-controller.ts
Labels: api: clouddebugger, size: xl

#1081 fix(deps): Update source-map to 0.8.0-beta.0
  package.json
Labels: api: clouddebugger, size: xs

#1084 build!: update library to use Node 12
  .github/.OwlBot.lock.yaml
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  package.json
  samples/package.json
  src/agent/debuglet.ts
  src/agent/io/scanner.ts
  src/agent/oneplatform-controller.ts
  src/agent/state/legacy-state.ts
  src/agent/v8/inspector-debugapi.ts
  src/agent/v8/legacy-debugapi.ts
  test/test-debuglet.ts
Labels: api: clouddebugger, size: m

#1088 feat!: upgrade to stable
  .repo-metadata.json
  README.md
Labels: api: clouddebugger, size: s
